version: "2.1"

services:
  myapp:
    image: alpine:3.5
    platform: linux/x86_64
    restart: always
    command: "sh -c 'while :; do sleep 1; done'"

  crontab:
    build: .
    platform: linux/x86_64
    restart: always
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
        APP_COMMENT: "test"
        APP_PROJECT: docker-crontab
        APP_SCHEDULE: "* * * * *"
        APP_COMMAND: echo world
        APP_CONTAINER: myapp
