name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker login docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
        docker build --pull --target nginx --file Dockerfile --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/docker-crontab" .
        docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/docker-crontab"
